### ISSUE TITLE
@Nullable and @NotNull Annotations

### ISSUE THREAD

**Issue by toteto** [hf/immu#12]
Provide `@Nullable` and `@NonNull` annotation for the getter methods depending on their `@Required` annotation

**Comment by hf** [comment]
OK, so here's a philosophical explanation as to why not:

Annotations are out-of-bound syntax. They convey information to the programmer, and to the annotation processor: *not* to the compiler. It's basically "meta-data." 

Annotations that help people / tools "infer nullability" don't actually serve a meaningful purpose. A better way, would be to use an Optional (a-la `java.util.Optional`) instance to convey the information "the value will most certainly be null sometimes" and you will be forcing the user of such an object to always anticipate `null` and, therefore NPEs.

So, yes, I / we should add support for `java.util.Optional` or anything that looks like `Optional`, instead of trying to find out whether the classpath supports `Nullable` or `NotNull`.
